const mapBaseUri = "https://assets.adaptedmind.com/mobile/v1/rive/map";
const monsterPartsBaseUri =
  "https://assets.adaptedmind.com/mobile/v1/rive/monster/parts";

const riveBaseUri = "https://assets.adaptedmind.com/mobile/v2/rive";

const monsterPartNames = [
  "baseballBat_m_1",
  "chefGlove_m_1",
  "headpart_1",
  "monster_1_pattern_1",
  "monster2_color_5",
  "pirateBelt_m_5",
  "baseballBat_m_2",
  "chefGlove_m_2",
  "headpart_2",
  "monster_1_pattern_2",
  "monster4_color_1",
  "pirateHat_m_1",
  "baseballBat_m_3",
  "chefGlove_m_3",
  "headpart_3",
  "monster_1_pattern_3",
  "monster4_color_2",
  "pirateHat_m_2",
  "baseballBat_m_4",
  "chefGlove_m_4",
  "headpart_4",
  "monster_1_pattern_4",
  "monster4_color_3",
  "pirateHat_m_3",
  "baseballBat_m_5",
  "chefGlove_m_5",
  "headpart_5",
  "monster_1_pattern_5",
  "monster4_color_4",
  "pirateHat_m_4",
  "baseballGlove_m_1",
  "chefHat_m_1",
  "heroCrown_m_1",
  "monster_2_pattern_1",
  "monster4_color_5",
  "pirateHat_m_5",
  "baseballGlove_m_2",
  "chefHat_m_2",
  "heroCrown_m_2",
  "monster_2_pattern_2",
  "monster5_color_1",
  "popcorn_m_1",
  "baseballGlove_m_3",
  "chefHat_m_3",
  "heroCrown_m_3",
  "monster_2_pattern_3",
  "monster5_color_2",
  "popcorn_m_2",
  "baseballGlove_m_4",
  "chefHat_m_4",
  "heroCrown_m_4",
  "monster_2_pattern_4",
  "monster5_color_3",
  "popcorn_m_3",
  "baseballGlove_m_5",
  "chefHat_m_5",
  "heroCrown_m_5",
  "monster_2_pattern_5",
  "monster5_color_4",
  "popcorn_m_4",
  "baseballHat_m_1",
  "chefSpoon_m_1",
  "jesterHat_m_1",
  "monster_3_color_0",
  "monster5_color_5",
  "popcorn_m_5",
  "baseballHat_m_2",
  "chefSpoon_m_2",
  "jesterHat_m_2",
  "monster_3_color_1",
  "mouth_1",
  "royalScepter_m_1",
  "baseballHat_m_3",
  "chefSpoon_m_3",
  "jesterHat_m_3",
  "monster_3_color_2",
  "mouth_2",
  "royalScepter_m_2",
  "baseballHat_m_4",
  "chefSpoon_m_4",
  "jesterHat_m_4",
  "monster_3_color_3",
  "mouth_3",
  "royalScepter_m_3",
  "baseballHat_m_5",
  "chefSpoon_m_5",
  "jesterHat_m_5",
  "monster_3_color_4",
  "mouth_4",
  "royalScepter_m_4",
  "blueScarf_m_1",
  "cowboyBoots_m_1",
  "jesterShoes_m_1",
  "monster_3_color_5",
  "mouth_5",
  "royalScepter_m_5",
  "blueScarf_m_2",
  "cowboyBoots_m_2",
  "jesterShoes_m_2",
  "monster_3_pattern_1",
  "necklace_m_1",
  "snowBoots_m_1",
  "blueScarf_m_3",
  "cowboyBoots_m_3",
  "jesterShoes_m_3",
  "monster_3_pattern_2",
  "necklace_m_2",
  "snowBoots_m_2",
  "blueScarf_m_4",
  "cowboyBoots_m_4",
  "jesterShoes_m_4",
  "monster_3_pattern_3",
  "necklace_m_3",
  "snowBoots_m_3",
  "blueScarf_m_5",
  "cowboyBoots_m_5",
  "jesterShoes_m_5",
  "monster_3_pattern_4",
  "necklace_m_4",
  "snowBoots_m_4",
  "bowTie_m_1",
  "cowboyHat_m_1",
  "knightArmour_m_1",
  "monster_3_pattern_5",
  "necklace_m_5",
  "snowBoots_m_5",
  "bowTie_m_2",
  "cowboyHat_m_2",
  "knightArmour_m_2",
  "monster_4_pattern_1",
  "paintBrush_m_1",
  "topHat_m_1",
  "bowTie_m_3",
  "cowboyHat_m_3",
  "knightArmour_m_3",
  "monster_4_pattern_2",
  "paintBrush_m_2",
  "topHat_m_2",
  "bowTie_m_4",
  "cowboyHat_m_4",
  "knightArmour_m_4",
  "monster_4_pattern_3",
  "paintBrush_m_3",
  "topHat_m_3",
  "bowTie_m_5",
  "cowboyHat_m_5",
  "knightArmour_m_5",
  "monster_4_pattern_4",
  "paintBrush_m_4",
  "topHat_m_4",
  "catHat_m_1",
  "cowboyVest_m_1",
  "knightHelm_m_1",
  "monster_4_pattern_5",
  "paintBrush_m_5",
  "topHat_m_5",
  "catHat_m_2",
  "cowboyVest_m_2",
  "knightHelm_m_2",
  "monster_5_pattern_1",
  "painterHat_m_1",
  "tuxedo_m_1",
  "catHat_m_3",
  "cowboyVest_m_3",
  "knightHelm_m_3",
  "monster_5_pattern_2",
  "painterHat_m_2",
  "tuxedo_m_2",
  "catHat_m_4",
  "cowboyVest_m_4",
  "knightHelm_m_4",
  "monster_5_pattern_3",
  "painterHat_m_3",
  "tuxedo_m_3",
  "catHat_m_5",
  "cowboyVest_m_5",
  "knightHelm_m_5",
  "monster_5_pattern_4",
  "painterHat_m_4",
  "tuxedo_m_4",
  "championMedal_m_1",
  "eyes_1",
  "knightShield_m_1",
  "monster_5_pattern_5",
  "painterHat_m_5",
  "tuxedo_m_5",
  "championMedal_m_2",
  "eyes_2",
  "knightShield_m_2",
  "monster1_color_1",
  "paintPalette_m_1",
  "wizardHat_m_1",
  "championMedal_m_3",
  "eyes_3",
  "knightShield_m_3",
  "monster1_color_2",
  "paintPalette_m_2",
  "wizardHat_m_2",
  "championMedal_m_4",
  "eyes_4",
  "knightShield_m_4",
  "monster1_color_3",
  "paintPalette_m_3",
  "wizardHat_m_3",
  "championMedal_m_5",
  "eyes_5",
  "knightShield_m_5",
  "monster1_color_4",
  "paintPalette_m_4",
  "wizardHat_m_4",
  "cheeseHat_m_1",
  "fanHand_m_1",
  "magicWand_m_1",
  "monster1_color_5",
  "paintPalette_m_5",
  "wizardHat_m_5",
  "cheeseHat_m_2",
  "fanHand_m_2",
  "magicWand_m_2",
  "monster2_color_1",
  "pirateBelt_m_1",
  "cheeseHat_m_3",
  "fanHand_m_3",
  "magicWand_m_3",
  "monster2_color_2",
  "pirateBelt_m_2",
  "cheeseHat_m_4",
  "fanHand_m_4",
  "magicWand_m_4",
  "monster2_color_3",
  "pirateBelt_m_3",
  "cheeseHat_m_5",
  "fanHand_m_5",
  "magicWand_m_5",
  "monster2_color_4",
  "pirateBelt_m_4",
];

type ReferencedAssetsMap = {
  map: ReferencedAssets;
};

type RiveAssetSource = {
  source: number | { uri: string };
};

type ReferencedAssets = {
  referencedAssets: Record<string, RiveAssetSource>;
  uri: string;
};

const monsterAssets = Object.fromEntries(
  monsterPartNames.map((part) => [
    part,
    { source: { uri: `${monsterPartsBaseUri}/${part}.webp` } },
  ])
);

export const riveAssets: ReferencedAssetsMap = {
  map: {
    referencedAssets: {
      Lemon: { source: { uri: `${mapBaseUri}/Lemon-Regular.ttf` } },
      map1: { source: { uri: `${mapBaseUri}/map1-2.webp` } },
      map2: { source: { uri: `${mapBaseUri}/map2-2.webp` } },
      map3: { source: { uri: `${mapBaseUri}/map3-2.webp` } },
      map4: { source: { uri: `${mapBaseUri}/map4-2.webp` } },
      ...monsterAssets,
    },
    uri: `${riveBaseUri}/map-v1.riv`,
  },
};
